on:
  push:
    branches: [ master ]

jobs:
  build-andeploy:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: sasie59/github-gh-pages-deploy-action@master
        with:
          keep_history: true
        env:
          ACCESS_TOKEN: ${{ serects.token }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run deploy

