on:
  push:
    branches: 
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-gh-pages-deploy-action@master
        with:
          keep_history: true
        env:
          ACCESS_TOKEN: ${{ secrts.token }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run deploy

